version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gym_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  php:
    build: .  # ✅ Usa tu Dockerfile personalizado
    container_name: gym_mongo_php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mongodb

volumes:
  mongo_data:
